#include <dirent.h>
#include <fcntl.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <termios.h>
#include <time.h>
#include <unistd.h>
#include <wait.h>
#include "ls.h"
#include "pwd.h"
#include "cd.h"
#include "user@host.h"
#include "pinfo.h"
#include "echo.h"
#include "nightswatch.h"
#include "kjob.c"